version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - POSTGRES_CONN=postgres://postgres:123456@db:5432/tender?sslmode=disable
      - POSTGRES_JDBC_URL=jdbc:postgresql://db:5432/tender
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=tender

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tender
    ports:
      - "5433:5432"
